FPTBook_Group/Areas/Authenticated/Controllers/BookController.cs
using FPTBook_Group.Data;
using FPTBook_Group.Models;
using FPTBook_Group.ModelsCRUD.Book;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FPTBook_Group.Areas.Authenticated.Controllers
{
<<<<<<< HEAD
    public class BookController : Controller
    {
        string global_image_change_url = "";
        private readonly ApplicationDbContext context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public BookController(ApplicationDbContext context, IWebHostEnvironment webHost)
        {
            this.context = context;
            webHostEnvironment = webHost;
        }
        [HttpGet]
        public async Task<IActionResult> BookIndex()
        {
            var book = await context.Books.Include(_ => _.Category).Include(_ => _.PublishCompany).ToListAsync();
            return View(book);
        }
        [HttpGet]
        public IActionResult CreateBook()
        {
            ViewBag.Category_id = new SelectList(context.Categories, "CategoryId", "Name");
            ViewBag.Company_id = new SelectList(context.PublishCompanies, "PublishingCompanyId", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateBook(AddBookViewModel BookModel)
        {
            ViewBag.Category_id = new SelectList(context.Categories, "CategoryId", "Name", BookModel.CategoryId);
            ViewBag.Company_id = new SelectList(context.PublishCompanies, "PublishingCompanyId", "Name", BookModel.PublishCompanyId);
            string uniqueFileName = UploadedFile(BookModel);
            var book = new Book()
            {
                Name = BookModel.Name,
                Quantity = BookModel.Quantity,
                Price = BookModel.Price,
                Description = BookModel.Description,
                UpdateDate = BookModel.UpdateDate,
                Author = BookModel.Author,
                Image = uniqueFileName,
                FronImage = BookModel.FronImage,
                CategoryId = BookModel.CategoryId,
                PublishCompanyId = BookModel.PublishCompanyId,
                Category = BookModel.Category,
                PublishCompany = BookModel.PublishCompany
            };




            foreach (var bookitem in context.Books.ToList())
            {
                if (book.Name == bookitem.Name)
                {
                    var NewQuantity = bookitem.Quantity.ToString();
                    var StoredQuantity = book.Quantity.ToString();
                    int ToStoredQuantity = int.Parse(StoredQuantity) + int.Parse(NewQuantity);
                    bookitem.Quantity = ToStoredQuantity;
                    bookitem.UpdateDate = book.UpdateDate;
                    await context.SaveChangesAsync();
                    return RedirectToAction("BookIndex");
                }
            }

            context.Books.Attach(book);
            context.Entry(book).State = EntityState.Added;
            await context.Books.AddAsync(book);
            await context.SaveChangesAsync();
            return RedirectToAction("BookIndex");




        }
        [HttpGet]
        public async Task<IActionResult> ViewBook(int id)
        {
            ViewBag.Category_id = new SelectList(context.Categories, "CategoryId", "Name");
            ViewBag.Company_id = new SelectList(context.PublishCompanies, "PublishingCompanyId", "Name");
            var book = await context.Books.FirstOrDefaultAsync(x => x.BookId == id);
            if (book != null)
            {
                var viewmodel = new UpdateBookView()
                {
                    BookId = book.BookId,
                    Name = book.Name,
                    Quantity = book.Quantity,
                    Price = book.Price,
                    Description = book.Description,
                    UpdateDate = book.UpdateDate,
                    Author = book.Author,
                    Image = book.Image,
                    FronImage = book.FronImage,
                    CategoryId = book.CategoryId,
                    PublishCompanyId = book.PublishCompanyId

                };

                global_image_change_url = book.Image;
                return await Task.Run(() => View("ViewBook", viewmodel));
            }

            return RedirectToAction("BookIndex");
        }
        [HttpPost]
        public async Task<IActionResult> ViewBook(UpdateBookView model)
        {
            ViewBag.Category_id = new SelectList(context.Categories, "CategoryId", "Name", model.CategoryId);
            ViewBag.Company_id = new SelectList(context.PublishCompanies, "PublishingCompanyId", "Name", model.PublishCompanyId);
            var book = await context.Books.FirstOrDefaultAsync(x => x.BookId == model.BookId);
            string change_img = UploadedFile(model);
            if (book != null)
            {
                book.Name = model.Name;
                book.Quantity = model.Quantity;
                book.Price = model.Price;
                book.Description = model.Description;
                book.UpdateDate = model.UpdateDate;
                book.Author = model.Author;
                if (change_img != null)
                {
                    book.Image = change_img;
                }
                book.CategoryId = model.CategoryId;
                book.PublishCompanyId = model.PublishCompanyId;

                await context.SaveChangesAsync();
            }
            else
            {
                return NotFound("Book Not Found");

            }



            await context.SaveChangesAsync();

            return RedirectToAction("BookIndex");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteBook(UpdateBookView model)
        {
            var book = await context.Books.FindAsync(model.BookId);

            if (book != null)
            {
                context.Books.Remove(book);
=======
	public class BookController : Controller
	{
            string global_image_change_url = "";
            private readonly ApplicationDbContext context;
            private readonly IWebHostEnvironment webHostEnvironment;

            public BookController(ApplicationDbContext context, IWebHostEnvironment webHost)
            {
                this.context = context;
                webHostEnvironment = webHost;
            }
            [HttpGet]
            public async Task<IActionResult> BookIndex()
            {
                var book = await context.Books.Include(_ => _.Category).Include(_ => _.PublishCompany).ToListAsync();
                return View(book);
            }
            [HttpGet]
            public IActionResult CreateBook()
            {
                ViewBag.Category_id = new SelectList(context.Categories, "CategoryId", "Name");
                ViewBag.Company_id = new SelectList(context.PublishCompanies, "PublishingCompanyId", "Name");
                return View();
            }
            [HttpPost]
            public async Task<IActionResult> CreateBook(AddBookViewModel BookModel)
            {
                ViewBag.Category_id = new SelectList(context.Categories, "CategoryId", "Name", BookModel.CategoryId);
                ViewBag.Company_id = new SelectList(context.PublishCompanies, "PublishingCompanyId", "Name", BookModel.PublishCompanyId);
                string uniqueFileName = UploadedFile(BookModel);
                var book = new Book()
                {
                    Name = BookModel.Name,
                    Quantity = BookModel.Quantity,
                    Price = BookModel.Price,
                    Description = BookModel.Description,
                    UpdateDate = BookModel.UpdateDate,
                    Author = BookModel.Author,
                    Image = uniqueFileName,
                    FronImage = BookModel.FronImage,
                    CategoryId = BookModel.CategoryId,
                    PublishCompanyId = BookModel.PublishCompanyId,
                    Category = BookModel.Category,
                   
                };




                foreach (var bookitem in context.Books.ToList())
                {
                    if (book.Name == bookitem.Name)
                    {
                        var NewQuantity = bookitem.Quantity.ToString();
                        var StoredQuantity = book.Quantity.ToString();
                        int ToStoredQuantity = int.Parse(StoredQuantity) + int.Parse(NewQuantity);
                        bookitem.Quantity = ToStoredQuantity;
                        bookitem.UpdateDate = book.UpdateDate;
                        await context.SaveChangesAsync();
                        return RedirectToAction("BookIndex");
                    }
                }

                context.Books.Attach(book);
                context.Entry(book).State = EntityState.Added;
                await context.Books.AddAsync(book);
                await context.SaveChangesAsync();
                return RedirectToAction("BookIndex");




            }
            [HttpGet]
            public async Task<IActionResult> ViewBook(int id)
            {
                ViewBag.Category_id = new SelectList(context.Categories, "CategoryId", "Name");
                ViewBag.Company_id = new SelectList(context.PublishCompanies, "PublishingCompanyId", "Name");
                var book = await context.Books.FirstOrDefaultAsync(x => x.BookId == id);
                if (book != null)
                {
                    var viewmodel = new UpdateBookView()
                    {
                        BookId = book.BookId,
                        Name = book.Name,
                        Quantity = book.Quantity,
                        Price = book.Price,
                        Description = book.Description,
                        UpdateDate = book.UpdateDate,
                        Author = book.Author,
                        Image = book.Image,

FPTBook_Group/Areas/Authenticated/Controllers/CategoryController.cs
using FPTBook_Group.Data;
using FPTBook_Group.Models;
using FPTBook_Group.ModelsCRUD.Category;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPTBook_Group.Areas.Authenticated.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext context;

        public CategoryController(ApplicationDbContext context)
        {
            this.context = context;
        }
        [HttpGet]
        public async Task<IActionResult> CategoryIndex()
        {
            var category = await context.Categories.Where(x => x.IsApproved).ToListAsync();
            return View(category);
        }
        public async Task<IActionResult> CategoryApproved()
        {
            var category = await context.Categories.ToListAsync();
            return View(category);
        }
        [HttpGet]
        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateCategory(AddCategoryViewModel CategoryModel)
        {
            var category = new Category()
            {
                Name = CategoryModel.Name,
                Description = CategoryModel.Description
            };

            await context.Categories.AddAsync(category);
            await context.SaveChangesAsync();
            return RedirectToAction("CategoryIndex");
        }
        [HttpGet]
        public async Task<IActionResult> ViewCategory(int id)
        {
            var category = await context.Categories.FirstOrDefaultAsync(x => x.CategoryId == id);

            if (category != null)
            {
                var viewmodel = new UpdateCategoryView()
                {
                    CategoryId = category.CategoryId,
                    Name = category.Name,
                    Description = category.Description
                };

                return await Task.Run(() => View("ViewCategory", viewmodel));
            }

            return RedirectToAction("CategoryIndex");
        }
        [HttpPost]
        public async Task<IActionResult> ViewCategory(UpdateCategoryView model)
        {
            var category = await context.Categories.FindAsync(model.CategoryId);
            if (category != null)
            {
                category.Name = model.Name;
                category.Description = model.Description;

                await context.SaveChangesAsync();

                return RedirectToAction("CategoryIndex");
            }

            return RedirectToAction("CategoryIndex");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteCategory(UpdateCategoryView model)
        {
            var category = await context.Categories.FindAsync(model.CategoryId);

            if (category != null)
            {
                context.Categories.Remove(category);


                await context.SaveChangesAsync();

                return RedirectToAction("CategoryIndex");
            }

            return RedirectToAction("CategoryIndex");
        }
        [HttpPost("{id}/approve")]
        public async Task<IActionResult> Approve(int id)
        {
            var category = await context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            category.IsApproved = true;
            context.SaveChanges();

            // code to notify store owner of category approval here

            return RedirectToAction(nameof(CategoryIndex));
        }

        [HttpPost("{id}/reject")]
        public async Task<IActionResult> Reject(int id)
        {
            var category = await context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            context.Categories.Remove(category);
            context.SaveChanges();

            // code to notify store owner of category rejection here

            return RedirectToAction(nameof(CategoryIndex));
        }
    }
}

FPTBook_Group/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] FPTBOOK_GROUP</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/FPTBook_Group/style.css" asp-append-version="true" />
	<link rel="icon" type="image/png" href="~/Images/icons/Rcode.png" asp-append-version="true" />
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/fonts/iconic/css/material-design-iconic-font.min.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/fonts/linearicons-v1.0.0/icon-font.min.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/vendor/animsition/css/animsition.min.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/vendor/daterangepicker/daterangepicker.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/vendor/slick/slick.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/vendor/MagnificPopup/magnific-popup.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/vendor/perfect-scrollbar/perfect-scrollbar.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/css/util.css" asp-append-version="true">
	<link rel="stylesheet" type="text/css" href="~/css/main.css" asp-append-version="true">
	<link rel="stylesheet" href="~/Shared/_Layout.cshtml.css" asp-append-version="true" />
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" asp-append-version="true" />
</head>
<body class="animsition">
	<header>
		<div class="container-menu-desktop">
			<!-- Topbar -->
			<div class="top-bar"
				 style="background-color:rgba(153, 159, 160, 0.94);
box-shadow: rgba(0, 0, 0, 0.25) 0px 14px 28px, rgba(0, 0, 0, 0.22) 0px 10px 10px;
">
				<div class="content-topbar flex-sb-m h-full container">
					<div class="left-top-bar" style="color:black">
						WELCOM TO FPT BOOKS - Developer By Group_Development
					</div>
				</div>
			</div>

			<div class="wrap-menu-desktop how-shadow1">
				<nav class="limiter-menu-desktop container mb-3">

					<!-- Logo desktop -->
					<a href="#" class="logo">
						<img src="~/Images/logo.png" alt="IMG-LOGO">
					</a>

					<!-- Menu desktop -->
					<div class="menu-desktop">
						<ul class="main-menu">
							<li>
								<a class="Title" asp-area="UnAuthenticated" asp-controller="Home"  asp-action="Index">FPT BOOOKS</a>

							</li>
							<li class="">
								<a asp-area="Authenticated" asp-controller="Category" asp-action="CategoryIndex">Category</a>
							</li>
							<li class="">
								<a asp-area="Authenticated" asp-controller="Book" asp-action="BookIndex">Book</a>

							</li>
						</ul>
					</div>

					<!-- Icon header -->
					<div class="wrap-icon-header flex-w flex-r-m">
						<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search">
							<i class="zmdi zmdi-search"></i>
						</div>

						<a asp-area="Authenticated" asp-controller="Cart" asp-action="CartIndex" class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti" data-notify="0">
							<i class="zmdi zmdi-shopping-cart"></i>
						</a>

						@* <a href="#" class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti" data-notify="0"> *@
						@* 	<i class="zmdi zmdi-favorite-outline"></i> *@
						@* </a> *@
					</div>
					<div class="navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom pl-5">
						<div class="how-shadow1 rounded-pill">
							<div class="navbar-collapse collapse justify-content-between container">
								<partial name="_LoginPartial" />
							</div>
						</div>
					</div>
					<div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
						<div class="container-search-header">
							<button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
								<img src="~/Images/icons/icon-close2.png" alt="CLOSE">
							</button>

							<form class="wrap-search-header flex-w p-l-15" method="get" asp-area="Authenticated" asp-controller="Book" asp-action="SearchBook">
								<button type="submit" class="flex-c-m trans-04">
									<i class="zmdi zmdi-search"></i>
								</button>
								<input class="plh3" type="text" name="Search" placeholder="Search...">
							</form>
						</div>
					</div>
				</nav>
			</div>
		</div>
	</header>

	<div class="container">
		<main role="main" class="pb-3 p-t-135">
			@RenderBody()
		</main>
	</div>

	<script src="~/vendor/jquery/jquery-3.2.1.min.js" asp-append-version="true"></script>
	<!--===============================================================================================-->
	<script src="~/vendor/animsition/js/animsition.min.js" asp-append-version="true"></script>
	<!--===============================================================================================-->
	<script src="~/vendor/bootstrap/js/popper.js" asp-append-version="true"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js" asp-append-version="true"></script>
	<!--===============================================================================================-->
	<script src="~/vendor/select2/select2.min.js" asp-append-version="true"></script>
	
	
	<!--===============================================================================================-->
	<script src="~/vendor/daterangepicker/moment.min.js" asp-append-version="true"></script>
	<script src="~/vendor/daterangepicker/daterangepicker.js" asp-append-version="true"></script>
	<!--===============================================================================================-->
	<script src="~/vendor/slick/slick.min.js" asp-append-version="true"></script>
	<script src="~/js/slick-custom.js" asp-append-version="true"></script>
	<!--===============================================================================================-->
	<script src="~/vendor/parallax100/parallax100.js" asp-append-version="true"></script>

	<!--===============================================================================================-->
	<script src="~/vendor/MagnificPopup/jquery.magnific-popup.min.js" asp-append-version="true"></script>
	
	<script src="~/vendor/isotope/isotope.pkgd.min.js" asp-append-version="true"></script>
	<script src="~/vendor/sweetalert/sweetalert.min.js" asp-append-version="true"></script>
	
	<script src="~/vendor/perfect-scrollbar/perfect-scrollbar.min.js" asp-append-version="true"></script>
	<script asp-append-version="true">
		$('.js-pscroll').each(function () {
			$(this).css('position', 'relative');
			$(this).css('overflow', 'hidden');
			var ps = new PerfectScrollbar(this, {
				wheelSpeed: 1,
				scrollingThreshold: 1000,
				wheelPropagation: false,
			});

			$(window).on('resize', function () {
				ps.update();
			})
		});
	</script>
	<script src="~/js/main.js" asp-append-version="true"></script>
	<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FPTBook_Group/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}